# https://github.com/golangci/golangci-lint#config-file
run:
  concurrency: 8
  timeout: 60s
  tests: false
linters: # Descriptions: https://github.com/golangci/awesome-go-linters
  # To see those enabled by default `golangci-lint help linters`
  enable: # These are disabled by default by golangci-lint
    - dogsled
    - gochecknoinits
    - goconst
    - godox
    - goimports
    - gosec
    - nolintlint
    - revive # https://revive.run/docs#golangci-lint
    - rowserrcheck
    - stylecheck
    - unparam
linters-settings:
  goimports:
    local-prefixes: github.com/skormos
issues:
  exclude-use-default: false
severity:
  default-severity: error
  case-sensitive: false
  rules:
    - text: 'SA1019:' # The Deprecated warning for 'staticcheck'
      severity: warn